### ISSUE TITLE
Build failure: jvb-api-client

### ISSUE THREAD

**Issue by baldrianbandit** [celogeek/jitsi-meet-arch#1]
Hi celogeek. On building jitsi-videobridge, I get the following error:
`[ERROR] Failed to execute goal on project jvb-api-client: Could not resolve dependencies for project org.jitsi:jvb-api-client:jar:2.1-SNAPSHOT: Could not find artifact org.jitsi:jvb-api-common:jar:2.1-SNAPSHOT -> [Help 1]`

**Comment by celogeek** [comment]
fixed
